UILayer/Controllers/ValidationController.cs
using DataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UILayer.Models;
using System.Web.Security;
using DataAccessLayer.Services;
using System.Web.UI.WebControls;
using System.Net.Mail;
using System.Net;

namespace UILayer.Controllers
{
    public class ValidationController : Controller
    {

        // GET: Validation
        public ActionResult Index()
        {
            return View();
        }

        private string GenerateAlphanumericCaptcha()
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%&?|0123456789";
            var random = new Random();
            return new string(Enumerable.Repeat(chars, 5).Select(s => s[random.Next(s.Length)]).ToArray());
        }
        public ActionResult CustomerRegistration()
        {

            // Generate and store captcha value in session
            var captchaValue = GenerateAlphanumericCaptcha();
            Session["Captcha"] = captchaValue;

            // Pass captcha value to the view
            var user = new UserModel();
            user.CaptchaValue = captchaValue;
            return View(user);
        }
        private bool ValidateCaptcha(string userInput)
        {
            var captchaInSession = Session["Captcha"] as string;
            return !string.IsNullOrEmpty(captchaInSession) && userInput.Trim().Equals(captchaInSession, StringComparison.OrdinalIgnoreCase);
        }
        [HttpPost]
        public ActionResult CustomerRegistration(UserModel user, string captchaInput)
        {
            InsuranceDbContext context = new InsuranceDbContext();
            bool cust = context.Customers.Any(e => e.Email == user.EmailAddress);
            bool cust1 = context.Customers.Any(e => e.UserName == user.UserName);
            if (ModelState.IsValid)
            {
                // Validate captcha
                if (!ValidateCaptcha(captchaInput))
                {
                    ModelState.AddModelError("Captcha", "Captcha verification failed.");
                    return View("CustomerRegistration", user);
                }

                // Check if email or username already registered
                if (cust)
                {
                    ModelState.AddModelError("Email", "Email already registered with us.");
                    return View("CustomerRegistration", user);
                }
                else if (cust1)
                {
                    ModelState.AddModelError("UserName", "Username already registered with us.");
                    return View("CustomerRegistration", user);
                }
                Customer newcustomer = new Customer
                {
                    Email = user.EmailAddress,
                    UserName = user.UserName,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PhoneNumber = user.PhoneNumber,
                    RoleId = 1,
                    Password = user.Password,
                };
                context.Customers.Add(newcustomer);
                context.SaveChanges();

                MailMessage MM = new MailMessage("sparkinsurancepolicy@gmail.com", user.EmailAddress);
                MM.Subject = "Account Registration Successfull";
                MM.Body = "Dear Customer," + "\n\n" +
                          "We are pleased to informed you that you registration request for SPARK Insurance Company has been successful!" + "\n\n\n" +
                          $"Full Name :{user.FirstName} {user.LastName}" + "\n" +
                          $"Email Id              :{user.EmailAddress}" + "\n" +
                          $"Phone Number  :{user.PhoneNumber}" + "\n" +
                          $"User Name          :{user.UserName}" + "\n" +
                          $"Password           :{user.Password}" + "\n" +
                          $"Registrastion Date {DateTime.Now}" + "\n\n\n\n" +
                         "For further assistance, kindly contact our agents" + "\n\n" +
                         "Puli Kavya    Contact Number:9988776655" + "\n" +
                         "Suresh Reddy  Contact Number:6655998877" + "\n\n\n\n" +
                         "Warm regards," + "\n" + "Spark and Allied Insurance Co.Ltd" + "\n" + "Hyderabad,Telangana";

                MM.IsBodyHtml = false;
                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Host = "smtp.gmail.com";
                smtpClient.Port = 587;
                smtpClient.EnableSsl = true;
                NetworkCredential networkCredential = new NetworkCredential("sparkinsurancepolicy@gmail.com", "rtfp wcpa wlbr vibq");
                smtpClient.UseDefaultCredentials = true;
                smtpClient.Credentials = networkCredential;
                smtpClient.Send(MM);

                return RedirectToAction("Dashboard", "Customer");
            }
            return View(user);
        }

        public ActionResult AdminRegistration()
        {
            // Generate and store captcha value in session
            var captchaValue = GenerateAlphanumericCaptcha();
            Session["Captcha"] = captchaValue;

            // Pass captcha value to the view
            var user = new UserModel();
            user.CaptchaValue = captchaValue;
            return View(user);
        }
        [HttpPost]
        public ActionResult AdminRegistration(UserModel user, string captchaInput)
        {
            InsuranceDbContext context = new InsuranceDbContext();
            bool cust = context.Admins.Any(e => e.EmailAddress == user.EmailAddress);
            bool cust1 = context.Admins.Any(e => e.UserName == user.UserName);
            if (ModelState.IsValid)
            {
                // Validate captcha
                if (!ValidateCaptcha(captchaInput))
                {
                    ModelState.AddModelError("Captcha", "Captcha verification failed.");
                    return View("AdminRegistration", user);
                }

                // Check if email or username already registered
                if (cust)
                {
                    ModelState.AddModelError("Email", "Email already registered with us.");
                    return View("AdminRegistraion", user);
                }
                else if (cust1)
                {
                    ModelState.AddModelError("UserName", "Username already registered with us.");
                    return View("AdminRegistration", user);
                }
                Admin newadmin = new Admin
                {
                    EmailAddress = user.EmailAddress,
                    UserName = user.UserName,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PhoneNumber = user.PhoneNumber,
                    RoleId = 1,
                    Password = user.Password,
                };
                context.Admins.Add(newadmin);
                context.SaveChanges();
                MailMessage MM = new MailMessage("sparkinsurancepolicy@gmail.com", user.EmailAddress);
                MM.Subject = "Account Registration Successfull";
                MM.Body = "Dear Employee," + "\n\n" +
                          "We are pleased to informed you that you registration request for SPARK Insurance Company has been successful!" + "\n\n\n" +
                          $"Full Name :{user.FirstName} {user.LastName}" + "\n" +
                          $"Email Id              :{user.EmailAddress}" + "\n" +
                          $"Phone Number  :{user.PhoneNumber}" + "\n" +
                          $"User Name          :{user.UserName}" + "\n" +
                          $"Password           :{user.Password}" + "\n" +
                          "Role                     :Admin" + "\n" +
                          $"Registrastion Date {DateTime.Now}" + "\n\n\n\n" +

                         "Warm regards," + "\n" + "Spark and Allied Insurance Co.Ltd" + "\n" + "Hyderabad,Telangana";

                MM.IsBodyHtml = false;
                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Host = "smtp.gmail.com";
                smtpClient.Port = 587;
                smtpClient.EnableSsl = true;
                NetworkCredential networkCredential = new NetworkCredential("sparkinsurancepolicy@gmail.com", "rtfp wcpa wlbr vibq");
                smtpClient.UseDefaultCredentials = true;
                smtpClient.Credentials = networkCredential;
                smtpClient.Send(MM);


                return RedirectToAction("Dashboard", "Admin");
            }
            return View(user);
        }
        public ActionResult GenerateCaptchaImage()
        {
            var captchaValue = GenerateAlphanumericCaptcha();

            // Store captcha value in session
            Session["Captcha"] = captchaValue;

            // Create an image of the captcha
            var captchaImage = LoginCaptcha.GenerateCaptchaImage(captchaValue);

            // Convert the image to a byte array and return it as an image response
            var imageBytes = LoginCaptcha.ImageToByteArray(captchaImage);

            return File(imageBytes, "image/png");
        }
        public ActionResult CustomerLogin()
        {
            // Generate and store captcha value in session
            var captchaValue = GenerateAlphanumericCaptcha();
            Session["Captcha"] = captchaValue;
            // Pass captcha value to the view
            var user = new LoginModel();
            user.CaptchaValue = captchaValue;
            return View(user);
        }
        [HttpPost]
        public ActionResult CustomerLogin(LoginModel loginView, string captchaInput)
        {

            var isCustomer = Authentication.VerifyCustomerCredentials(loginView.UserName, loginView.Password);

            // Validate captcha
            if (!ValidateCaptcha(captchaInput))

UILayer/Views/Validation/AdminLogin.cshtml
@model UILayer.Models.LoginModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-image: url('../../content/bg-transformed.jpeg');
            margin: 0;
            padding: 0;
            background-color: rgba(0,0,0,0.5);
            background-blend-mode: overlay;
            background-size: cover;
            background-position: right;
            min-height: 100vh;
            background-repeat: no-repeat;
        } 

        .container {
            width: 80%;
            margin: 0 auto;
        }

        h2 {
            color: #fff;
        }

        .form-horizontal {
            margin-top: 20px;
        }

        .text-danger {
            color: #d9534f;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .control-label {
            font-weight: bold;
        }

        .form-control {
            width: 100%;
            padding: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .btn-default {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

            .btn-default:hover {
                background-color: #45a049;
            }

        .form-horizontal label {
            color: #fff;
        }

        .form-horizontal input {
            background-color: transparent;
            outline: none;
            border: 1px solid #fff;
            color: #fff;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Admin Login</h2>

        @using (Html.BeginForm("AdminLogin", "Validation", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.UserName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.UserName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Captcha:</label>
                <div class="col-md-8">
                    <img id="captchaImage" src="@Url.Action("GenerateCaptchaImage", "Validation")" alt="Captcha Image" />
                    <img id="refreshCaptchaButton" src="~/Content/Refresh.jpg" alt="Refresh Captcha" onclick="refreshCaptcha()" style="cursor: pointer; width: 20px; height: 20px;" />
                    @Html.TextBox("captchaInput", null, new { @class = "form-control" })
                    @Html.ValidationMessage("captchaInput")
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Login</button>
                </div>
            </div>
        }
        <br /><br />
        @using (Html.BeginForm("AdminResetPassword", "Validation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Forget Password?</button>
                </div>
            </div>
        }
    </div>
</body>
</html>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
  function refreshCaptcha() {
            // Get the captcha image element
            var captchaImage = document.getElementById('captchaImage');
            // Update the captcha image source to get a new captcha
            captchaImage.src = '@Url.Action("GenerateCaptchaImage", "Validation")?' + new Date().getTime();
            // Clear the previous captcha input value
            document.getElementById('captchaInput').value = '';
        }
    </script>
}

UILayer/Views/Validation/AdminRegistration.cshtml
@model UILayer.Models.UserModel

@{
    ViewBag.Title = "AdminRegistration";
}
<style>

    body {
        font-weight: bold;
        background-image: url('../../content/bg-transformed.jpeg');
        background-color: rgba(0,0,0,0.5);
        background-blend-mode: overlay;
        background-size: cover;
        background-position: right;
        background-repeat: no-repeat;
    }

    .form-horizontal label {
        color: #fff;
    }


    .form-horizontal input {
        background-color: transparent;
        outline: none;
        border: 1px solid #fff;
        color: #fff;
    }
</style>
@*<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>*@
<div class="container-fluid">
    <h2 class="text-white">New Registration</h2>
</div>
@using (Html.BeginForm("AdminRegistration", "Validation", FormMethod.Post, new { id = "adminRegistrationForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, "Enter First Name :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Enter Last Name :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, "Enter Email :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EmailAddress, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, "Enter Username:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, "Enter Phone Number:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, "Enter Password :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, "Enter to Confirm Password : ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Captcha:</label>
            <div class="col-md-8">
                <img id="captchaImage" src="@Url.Action("GenerateCaptchaImage", "Validation")" alt="Captcha Image" />
                <img id="refreshCaptchaButton" src="~/Content/Refresh.jpg" alt="Refresh Captcha" onclick="refreshCaptcha()" style="cursor: pointer; width: 20px; height: 20px;" />
                @Html.TextBox("captchaInput", null, new { @class = "form-control" })
                @Html.ValidationMessage("captchaInput")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <input type="button" value="Reset" class="ms-2 btn btn-warning" onclick="resetForm('AdminRegistrationForm')" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function resetForm(formId) {
            var form = document.getElementById(formId);

            // Reset the form fields
            form.reset();

            // Clear validation messages
            var validationMessages = form.querySelectorAll('[data-valmsg-for]');
            for (var i = 0; i < validationMessages.length; i++) {
                validationMessages[i].innerHTML = ''; // Clear validation messages
                validationMessages[i].style.display = 'none'; // Hide the error message container
            }
    }
    function refreshCaptcha() {
            // Get the captcha image element
            var captchaImage = document.getElementById('captchaImage');

            // Update the captcha image source to get a new captcha
            captchaImage.src = '@Url.Action("GenerateCaptchaImage", "Validation")?' + new Date().getTime();

            // Clear the previous captcha input value
            document.getElementById('captchaInput').value = '';
        }
    </script>
}

UILayer/Views/Validation/AdminResetPassword.cshtml
@model UILayer.Models.ResetPasswordModel

@{
    ViewBag.Title = "Reset Password";
}
<style>
    
    body {
        font-weight: bold;
        background-image: url('../../content/bg-transformed.jpeg');
        background-color: rgba(0,0,0,0.5);
        height:100vh;
        background-blend-mode: overlay;
        background-size: cover;
        background-position: right;
        background-repeat: no-repeat;
    }

    .form-horizontal label {
        color: #fff;
    }

    .form-horizontal input {
        background-color: transparent;
        outline: none;
        border: 1px solid #fff;
        color: #fff;
    }
</style>

<h2 style="margin-left:280px " class="text-white"> Reset Password</h2>
<div class="container d-flex align-items-center justify-content-center">

    @using (Html.BeginForm("AdminResetPassword", "Validation", FormMethod.Post, new { @class = "col-md-6" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal mt-1">
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, "Enter Username :", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Password, "Enter New Passwrd:", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group ">
            <div class="col-12">
                @Html.LabelFor(model => model.ConfirmPassword, "Enter Password Again:", htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col">
                <div class="input-group">
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" value="Reset Password" class="btn btn-outline-primary" />
                <a href="javascript:history.back()" class="btn btn-outline text-white" >Back</a>
            </div>
        </div>
    </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UILayer/Views/Validation/CustomerLogin.cshtml
@model  UILayer.Models.LoginModel

@{
    ViewBag.Title = "Login";
}
<style>

    body {
        font-family: 'Arial', sans-serif;
        background-image: url('../../content/bg-transformed.jpeg');
        margin: 0;
        padding: 0;
        background-color: rgba(0,0,0,0.5);
        background-blend-mode: overlay;
        background-size: cover;
        background-position: right;
        min-height: 100vh;
        background-repeat: no-repeat;
    }

    .container {
        width: 80%;
        margin: 0 auto;
    }

    h2 {
        color: #fff;
    }

    .form-horizontal {
        margin-top: 20px;
    }

    .text-danger {
        color: #d9534f;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .control-label {
        font-weight: bold;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    .btn-default {
        background-color: #4caf50;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        .btn-default:hover {
            background-color: #45a049;
        }

    .form-horizontal label {
        color: #fff;
    }

    .form-horizontal input {
        background-color: transparent;
        outline: none;
        border: 1px solid #fff;
        color: #fff;
    }
</style>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<body>
    <div class="container">
        <br />
        <h2>Customer Login</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @using (Html.BeginForm("CustomerLogin", "Validation", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.UserName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.UserName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Captcha:</label>
                <div class="col-md-8">
                    <img id="captchaImage" src="@Url.Action("GenerateCaptchaImage", "Validation")" alt="Captcha Image" />
                    <img id="refreshCaptchaButton" src="~/Content/Refresh.jpg" alt="Refresh Captcha" onclick="refreshCaptcha()" style="cursor: pointer; width: 20px; height: 20px;" />
                    @Html.TextBox("captchaInput", null, new { @class = "form-control" })
                    @Html.ValidationMessage("captchaInput")
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Login</button>
                </div>
            </div>


        }
        <br /><br />
        @using (Html.BeginForm("CustomerResetPassword", "Validation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">Forgot Password?</button>
                </div>


            </div>
        }
    </div>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>  function refreshCaptcha() {
            // Get the captcha image element
            var captchaImage = document.getElementById('captchaImage');
            // Update the captcha image source to get a new captcha
            captchaImage.src = '@Url.Action("GenerateCaptchaImage", "Validation")?' + new Date().getTime();
            // Clear the previous captcha input value
            document.getElementById('captchaInput').value = '';
        }
    </script>
}

UILayer/Views/Validation/CustomerResetPassword.cshtml
@model UILayer.Models.ResetPasswordModel

@{
    ViewBag.Title = "Reset Password";
}
<style>
    body {
        font-weight: bold;
        background-image: url('../../content/bg-transformed.jpeg');
        background-color: rgba(0,0,0,0.5);
        background-blend-mode: overlay;
        background-size: cover;
        height: 100vh;
        background-position: right;
        background-repeat: no-repeat;
    }

    .form-horizontal label {
        color: #fff;
    }

    .form-horizontal input {
        background-color: transparent;
        outline: none;
        border: 1px solid #fff;
        color: #fff;
    }
</style>
<h2 style="margin-left:280px"> Forgot Password</h2>
<div class="container d-flex align-items-center justify-content-center">

    @using (Html.BeginForm("CustomerResetPassword", "Validation", FormMethod.Post, new { @class = "col-md-6" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal mt-1">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, "Enter Username :", htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.Password, "Enter New Passowrd:", htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-8">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group ">
                <div class="col-12">
                    @Html.LabelFor(model => model.ConfirmPassword, "Enter Password Again:", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col">
                    <div class="input-group">
                        @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Captcha:</label>
                <div class="col-md-8">
                    <img id="captchaImage" src="@Url.Action("GenerateCaptchaImage", "Validation")" alt="Captcha Image" />
                    <img id="refreshCaptchaButton" src="~/Content/Refresh.jpg" alt="Refresh Captcha" onclick="refreshCaptcha()" style="cursor: pointer; width: 20px; height: 20px;" />
                    @Html.TextBox("captchaInput", null, new { @class = "form-control" })
                    @Html.ValidationMessage("captchaInput")
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <input type="submit" value="Reset Password" class="btn btn-primary" />
                    <a href="javascript:history.back()"  class="btn btn-outline text-white">Back</a>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}